
version: '3'

services:
  pizza-sql:
    container_name: pizza-sql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    network_mode: bridge
    restart: "no"

  pizza-repo:
    privileged: true
    container_name: pizza-repo-0.1
    image: urieluvd/laravel-5.4:latest
    ports:
      - 8000:8000
      - 80:80
    volumes:
      - "/c/Users/Arturo/Documents/docker/pizza-time:/var/www/html/pizza-time"
    restart: "no"
    network_mode: bridge
    links:
     - pizza-sql:mysql
    command: tail -f /dev/null
    tty: true